"""Album unique constraints

Revision ID: 2008219c2861
Revises: 74df8fa5a35f
Create Date: 2019-02-09 20:58:43.822325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2008219c2861'
down_revision = '74df8fa5a35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'metadata_format', existing_type=sa.VARCHAR(length=7),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'metadata_format', existing_type=sa.VARCHAR(length=7),
                    nullable=True)
    # ### end Alembic commands ###

