
default_context:
    bitbucket_repo: "mishmash"
    bitbucket_url: "https://bitbucket.org/bitbucket-user/mishmash"
    bitbucket_username: "bitbucket-user"
    default_locale: "en_US"
    email: "travis@pobox.com"
    full_name: "Travis Shirk"
    gettext_domain: "MishMash"
    github_repo: "MishMash"
    github_url: "https://github.com/nicfit/MishMash"
    github_username: "nicfit"
    intended_audience: "End Users/Desktop"
    license: "GNU GPL v3.0"
    project_long_description: ""
    project_name: "MishMash"
    project_short_description: "Music database and web interface."
    project_slug: "mishmash"
    py26: "no"
    py27: "no"
    py33: "no"
    py34: "no"
    py35: "no"
    py36: "yes"
    py37: "yes"
    py_module: "mishmash"
    pyapp_type: "normal"
    pypi_repo_name: "MishMash"
    pypi_username: "nicfit"
    pypy: "no"
    pypy3: "no"
    release_date: "today"
    src_dir: "."
    use_bitbucket: "no"
    use_github: "yes"
    use_make: "yes"
    use_paver: "no"
    use_pypi_deployment_with_travis: "no"
    use_pytest: "yes"
    use_rtd: "no"
    use_travis_ci: "yes"
    version: "0.3b12"
    web: "https://github.com/nicfit/MishMash"
    year: "2013-2019"
