#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    CREATE DATABASE ${DB_NAME};
    CREATE USER ${DB_USER};
    ALTER USER ${DB_USER} WITH SUPERUSER;
    ALTER USER ${DB_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL
