FROM mishmash-arch
MAINTAINER Travis Shirk <travis@pobox.com>

ENV MM_HOME /MishMash
ENV USER mishmash
ENV HOME /home/$USER

RUN pacman -S --noconfirm gcc git postgresql-libs vim

RUN useradd -m ${USER} -d ${HOME}
RUN echo "source ${MM_HOME}/bin/activate" >> ${HOME}/.bashrc && \
    echo "alias ll='ls -l'" >> ${HOME}/.bashrc

RUN mkdir $MM_HOME && chown $USER:$USER $MM_HOME

USER $USER
RUN virtualenv $MM_HOME
RUN git clone https://github.com/nicfit/mishmash.git ${MM_HOME}/src
RUN source ${MM_HOME}/bin/activate && \
    pip install -r ${MM_HOME}/src/requirements/default.txt && \
    pip install -r ${MM_HOME}/src/requirements/test.txt && \
    pip install -r ${MM_HOME}/src/requirements/dev.txt && \
    cd ${MM_HOME}/src && python setup.py install


#RUN source ${HOME}/bin/activate && \
#    mishmash info

CMD ["/bin/bash"]
