FROM mishmash-arch
MAINTAINER Travis Shirk <travis@pobox.com>

RUN pacman -S --noconfirm gcc git vim

COPY ./src/requirements.txt ${MM_HOME}/src/requirements.txt
RUN source ${MM_HOME}/bin/activate && \
    pip install -U pip && \
    pip install -U ipdb && \
    pip install -r ${MM_HOME}/src/requirements.txt
RUN source ${MM_HOME}/bin/activate && \
    # FIXME: I guess this needs to be moved from dev to requirements
    pip install pyramid_debugtoolbar

# Copy rest of source
COPY ./src/ ${MM_HOME}/src/
##RUN git clone https://github.com/nicfit/MishMash.git ${MM_HOME}/src
RUN source ${MM_HOME}/bin/activate && \
    cd ${MM_HOME}/src && python setup.py install

RUN chown -R $USER:$USER $MM_HOME

# user root above ^^^^
# -------------------------
# user mishmash below vvvv

USER $USER
ENV LANG en_US.UTF-8

CMD ["/MishMash/bin/mishmash-init"]
#CMD ["/bin/bash"]

COPY config.ini ${MM_HOME}/etc/
COPY mishmash-init ${MM_HOME}/bin/
