main:
    - eyeD3>=0.8
    # When pinning nicfit.py be sure to also pin nicfit[cookiecutter] below
    - nicfit.py>=0.8b3
    - SQLAlchemy
    - inotify
    - alembic
    - countrycode
    - pyfiglet
    - sqlalchemy-utils

extra_postgres:
    - psycopg2-binary

extra_web:
    - pyramid
    - pyramid_chameleon
    - pyramid-layout
    - pyramid_tm
    - transaction
    - zope.sqlalchemy
    - waitress
    - pyramid-debugtoolbar

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-postgres
    - faker
    - factory-boy

dev:
    - nicfit.py[cookiecutter]>=0.8b3
    - Sphinx
    - sphinx_rtd_theme
    - babel
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git@nicfit.py
    - ipdb
    - pip-tools
    - tox
    - twine
    - wheel
    - pyaml
    - pss
