main:
    - eyeD3~=0.9
    - nicfit.py
    - SQLAlchemy
    - inotify
    - alembic
    - countrycode
    - pyfiglet
    - sqlalchemy-utils
    - psycopg2-binary

extra_web:
    - pyramid
    - pyramid_chameleon
    - pyramid-layout
    - pyramid_tm
    - transaction
    - zope.sqlalchemy
    - waitress>=1.4.3
    - pyramid-debugtoolbar
    - gevent
    - gunicorn

extra_tools:
    - inquirer

test:
    - tox
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-postgres
    - faker
    - factory-boy

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    - babel
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git@nicfit.py
    - pip-tools
    - twine
    - wheel
    - pyaml
    - pss
