main:
    - eyeD3>=0.8.0b0
    - nicfit.py
    - SQLAlchemy
    - inotify
    - alembic
    - countrycode
    - pyfiglet
    - sqlalchemy-utils

extra_postgres:
    - psycopg2

extra_web:
    - pyramid
    - pyramid_chameleon
    - pyramid-layout
    - pyramid_tm
    - transaction
    - zope.sqlalchemy
    - waitress
    - pyramid-debugtoolbar

test:
    - pytest
    - pytest-cov
    - pytest-runner
    - faker
    - factory-boy

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - babel
    - check-manifest
    - flake8
    - git+https://github.com/nicfit/gitchangelog.git
    - ipdb
    - pip-tools
    - tox
    - twine
    - watchdog
    - wheel
    - sphinx_bootstrap_theme
